#!/bin/bash

while getopts 'uh' OPTION; do
  case "$OPTION" in
    u)
        grep  -lrnw  . -e $2 --exclude terraform.tfstate* --exclude-dir set-project-id* --exclude-dir .terraform \
| xargs -I@ sed -i '' "s/$2/\<PROJECT_ID\>/g" @
    exit 1
    ;;
    h)
        echo "set-project-id [-uh] project-id $2"
        exit 1
        ;;
    esac
    done

grep  -lrnw  . -e "<PROJECT_ID>" --exclude terraform.tfstate* --exclude set-project-id* --exclude-dir .terraform \
| xargs -I@ sed -i '' "s/\<PROJECT_ID\>/$1/g" @
